volumes:
  node_modules: {}

services:
  workspace:
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: .
    command: /bin/sh -c 'while sleep 1000; do :; done'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app

  docs:
    build:
      dockerfile: ./.devcontainer/Dockerfile
      context: .
    command: /bin/sh -c 'npm ci && npm run dev'
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    working_dir: /app
    ports:
      - "127.0.0.1:8080:8080"
